program expTest;

uses
  Forms,
  AnimPlayer in '\\Kryster\Source\VCL\AnimPlayer.pas',
  AppHints in '\\Kryster\Source\VCL\AppHints.pas',
  AppSplash in '\\Kryster\Source\VCL\AppSplash.pas',
  AppTips in '\\Kryster\Source\VCL\AppTips.pas',
  BitBlt in '\\Kryster\Source\Graphics\BitBlt.pas',
  Buffer in '\\Kryster\Source\Graphics\Buffer.pas',
  BufferDraw in '\\Kryster\Source\Graphics\BufferDraw.pas',
  ChunkStream in '\\Kryster\Source\Graphics\ChunkStream.pas',
  CodingUtils in '\\Kryster\Source\Misc\CodingUtils.pas',
  ColorSpaces in '\\Kryster\Source\Graphics\ColorSpaces.pas',
  Debug in '\\Kryster\Source\Misc\Debug.pas',
  Dib2Frames in '\\Kryster\Source\GameAPI\Dib2Frames.pas',
  DibDraw in '\\Kryster\Source\Graphics\DibDraw.pas',
  DibRle in '\\Kryster\Source\Graphics\DibRle.pas',
  Dibs in '\\Kryster\Source\Graphics\Dibs.pas',
  DragDrop in '\\Kryster\Source\WinUtils\DragDrop.pas',
  DropTarget in '\\Kryster\Source\VCL\DropTarget.pas',
  DumpUtils in '\\Kryster\Source\Misc\DumpUtils.pas',
  FilenameUtils in '\\Kryster\Source\WinUtils\FilenameUtils.pas',
  FileOpUtils in '\\Kryster\Source\Misc\FileOpUtils.pas',
  FlicPlayer in '\\Kryster\Source\VCL\FlicPlayer.pas',
  Flics in '\\Kryster\Source\Graphics\Flics.pas',
  FliPlay in '\\Kryster\Source\Graphics\FliPlay.pas',
  FliPlayback in '\\Kryster\Source\Graphics\FliPlayback.pas',
  Gdi in '\\Kryster\Source\Graphics\Gdi.pas',
  GifPlayer in '\\Kryster\Source\VCL\GifPlayer.pas',
  Gifs in '\\Kryster\Source\Graphics\Gifs.pas',
  Icons in '\\Kryster\Source\WinUtils\Icons.pas',
  IconUtils in '\\Kryster\Source\VCL\IconUtils.pas',
  ImageLib in '\\Kryster\Source\GameAPI\ImageLib.pas',
  Images in '\\Kryster\Source\GameAPI\Images.pas',
  InstanceUtils in '\\Kryster\Source\VCL\InstanceUtils.pas',
  MiscUtils in '\\Kryster\Source\Misc\MiscUtils.pas',
  MsgBoxUtils in '\\Kryster\Source\WinUtils\MsgBoxUtils.PAS',
  NumUtils in '\\Kryster\Source\Misc\NumUtils.pas',
  MemUtils in '\\Kryster\Source\Misc\MemUtils.pas',
  Palettes in '\\Kryster\Source\Graphics\Palettes.pas',
  PaletteIO in '\\Kryster\Source\Graphics\PaletteIO.pas',
  PidlIcons in '\\Kryster\Source\WinUtils\PidlIcons.pas',
  RangeStrUtils in '\\Kryster\Source\Misc\RangeStrUtils.pas',
  Rects in '\\Kryster\Source\Graphics\Rects.pas',
  RegUtils in '\\Kryster\Source\WinUtils\RegUtils.pas',
  RiffIO in '\\Kryster\Source\Graphics\RiffIO.pas',
  RlePlayer in '\\Kryster\Source\VCL\RlePlayer.pas',
  RunUtils in '\\Kryster\Source\Misc\RunUtils.pas',
  SharedTimer in '\\Kryster\Source\Misc\SharedTimer.pas',
  ShellGUID in '\\Kryster\Source\WinUtils\ShellGUID.pas',
  ShellIcons in '\\Kryster\Source\WinUtils\ShellIcons.pas',
  Sprites in '\\Kryster\Source\GameAPI\Sprites.pas',
  StreamUtils in '\\Kryster\Source\Misc\StreamUtils.pas',
  StrUtils in '\\Kryster\Source\Misc\StrUtils.pas',
  SystemInfo in '\\Kryster\Source\WinUtils\SystemInfo.pas',
  TimerUtils in '\\Kryster\Source\WinUtils\TimerUtils.pas',
  UserUtils in '\\Kryster\Source\Misc\UserUtils.pas',
  VclUtils in '\\Kryster\Source\VCL\VclUtils.pas',
  VideoDraw in '\\Kryster\Source\Graphics\VideoDraw.pas',
  VideoICM in '\\Kryster\Source\Graphics\VideoICM.pas',
  VideoUtils in '\\Kryster\Source\Graphics\VideoUtils.pas',
  ViewUtils in '\\Kryster\Source\Misc\ViewUtils.pas',
  WinUtils in '\\Kryster\Source\WinUtils\WinUtils.pas',
  GifPlay in '\\Kryster\Source\Graphics\GifPlay.pas',
  AnimPlay in '\\Kryster\Source\Graphics\AnimPlay.pas',
  SpeedImage in '\\Kryster\Source\VCL\SpeedImage.pas',
  MiscEditors in '\\Kryster\Source\VCL\MiscEditors.pas',
  GraphEditors in '\\Kryster\Source\VCL\GraphEditors.pas',
  Toolbars in '\\Kryster\Source\VCL\Toolbars.pas',
  BufferClipbrd in '\\Kryster\Source\Graphics\BufferClipbrd.pas',
  RlePlay in '\\Kryster\Source\Graphics\RlePlay.pas',
  Gradients in '\\Kryster\Source\VCL\Gradients.pas',
  FileFolders in '\\Kryster\Source\WinUtils\FileFolders.pas',
  MappedFiles in '\\Kryster\Source\WinUtils\MappedFiles.pas',
  DirUtils in '\\Kryster\Source\WinUtils\DirUtils.pas',
  BrowseFolders in '\\Kryster\Source\WinUtils\BrowseFolders.pas',
  PidlPath in '\\Kryster\Source\WinUtils\PidlPath.pas',
  BitFonts in '\\Kryster\Source\GameAPI\BitFonts.pas',
  BufferColors in '\\Kryster\Source\Graphics\BufferColors.pas',
  ListUtils in '\\Kryster\Source\Misc\ListUtils.pas',
  CommRez in '\\Kryster\Source\VCL\CommRez.pas',
  BufferRle in '\\Kryster\Source\Graphics\BufferRle.pas',
  BufferProviders in '\\Kryster\Source\Graphics\BufferProviders.pas',
  ColorTrans in '\\Kryster\Source\Graphics\ColorTrans.pas',
  ColorQuant in '\\Kryster\Source\Graphics\ColorQuant.pas',
  GdiExt in '\\Kryster\Source\Graphics\GdiExt.pas',
  Regions in '\\Kryster\Source\Graphics\Regions.pas',
  SHLWAPI in '\\Kryster\Source\WinUtils\SHLWAPI.pas',
  CanvasBmp in '\\Kryster\Source\Graphics\CanvasBmp.pas',
  SpeedBmp in '\\Kryster\Source\Graphics\SpeedBmp.pas',
  SplashDesigner in 'SplashDesigner.pas' {fmSplashDesigner};

{$R *.RES}

begin
  Application.Initialize;
  Application.CreateForm(TfmSplashDesigner, fmSplashDesigner);
  Application.Run;
end.
