{$A+,B-,C+,D+,E-,F-,G+,H+,I+,J+,K-,L+,M-,N+,O-,P+,Q-,R-,S-,T-,U-,V+,W+,X+,Y-,Z1}
{$MINSTACKSIZE $00004000}
{$MAXSTACKSIZE $00100000}
{$IMAGEBASE $00400000}
{$APPTYPE GUI}

{ $DEFINE USELogs}

program FIVEModelServer;

uses
  ShareMem,
  Forms,
  ModelServerReportForm in 'ModelServerReportForm.pas' {ModelServerReport},
  ModelServer in 'ModelServer.pas',
  Population in '..\Kernel\Population.pas',
  World in '..\Kernel\World.pas',
  Kernel in '..\Kernel\Kernel.pas',
  Collection in '..\Kernel\Collection.pas',
  ClassStorageInt in '..\Class Storage\ClassStorageInt.pas',
  ClassStorage in '..\Kernel\ClassStorage.pas',
  Construction in '..\StdBlocks\Construction.pas',
  AsxCriticalSections in '..\Kernel\AsxCriticalSections.pas',
  OfficeBlock in '..\StdBlocks\OfficeBlock.pas',
  Trade in '..\Kernel\Trade.pas',
  ModelServerCache in '..\Cache\ModelServerCache.pas',
  CacheCommon in '..\Cache\CacheCommon.pas',
  KernelCache in '..\Kernel\KernelCache.pas',
  SpecialChars in '..\Cache\SpecialChars.pas',
  CacheAgent in '..\Cache\CacheAgent.pas',
  Plotter in '..\Kernel\Plotter.pas',
  Surfaces in '..\Surfaces\Surfaces.pas',
  PyramidalModifier in '..\Surfaces\PyramidalModifier.pas',
  Protocol in '..\Protocol\Protocol.pas',
  StdFluids in '..\StdBlocks\StdFluids.pas',
  Persistent in '..\Kernel\Persistent.pas',
  MailServerInterfaces in '..\Mail\MailServerInterfaces.pas',
  Headquarters in '..\Kernel\Headquarters.pas',
  ResearchCenter in '..\Kernel\ResearchCenter.pas',
  WorkCenterBlock in '..\Kernel\WorkCenterBlock.pas',
  SimHints in '..\Kernel\SimHints.pas',
  Circuits in '..\Circuits\Circuits.pas',
  PublicFacility in '..\Kernel\PublicFacility.pas',
  Environmental in '..\StdBlocks\Environmental.pas',
  Standards in '..\Model Extensions\Standards.pas',
  ConnectedBlock in '..\Kernel\ConnectedBlock.pas',
  Land in '..\Land\Land.pas',
  SpontaneousBuildings in '..\Kernel\SpontaneousBuildings.pas',
  LargeMatrix in '..\Utils\Misc\LargeMatrix.pas',
  LandSurfaces in '..\Kernel\LandSurfaces.pas',
  MapCompress in '..\Kernel\MapCompress.pas',
  Matrix in '..\Utils\Misc\Matrix.pas',
  CompStringsParser in '..\Utils\Misc\CompStringsParser.pas',
  PopulatedBlock in '..\Kernel\PopulatedBlock.pas',
  Accounts in '..\Kernel\Accounts.pas',
  MetaInstances in '..\Kernel\MetaInstances.pas',
  BasicAccounts in '..\Kernel\BasicAccounts.pas',
  EvaluatedBlock in '..\StdBlocks\EvaluatedBlock.pas',
  Newspapers in '..\Kernel\Newspapers.pas',
  NewsServerInterfaces in '..\News Server\NewsServerInterfaces.pas',
  Disasters in '..\Kernel\Disasters.pas',
  Banks in '..\StdBlocks\Banks.pas',
  Broadcast in '..\StdBlocks\Broadcast.pas',
  StdBroadcast in '..\StdBlocks\StdBroadcast.pas',
  Transport in '..\Transport\Transport.pas',
  TransportInterfaces in '..\Transport\TransportInterfaces.pas',
  MatrixLayer in '..\Transport\MatrixLayer.pas',
  VisualClassManager in '..\Class Packer\VisualClassManager.pas',
  Taxes in '..\Kernel\Taxes.pas',
  BasicTaxes in '..\Kernel\BasicTaxes.pas',
  StdTaxes in '..\StdBlocks\StdTaxes.pas',
  MapStringToObject in '..\Utils\Misc\MapStringToObject.pas',
  Politics in '..\Kernel\Politics.pas',
  PoliticsCache in '..\Kernel\PoliticsCache.pas',
  BasicPolitics in '..\Kernel\BasicPolitics.pas',
  ActorTypes in '..\Actors\ActorTypes.pas',
  DistributedStates in '..\Actors\DistributedStates.pas',
  StateEngine in '..\Actors\StateEngine.pas',
  ActorPool in '..\Actors\ActorPool.pas',
  BasicCurriculum in '..\Kernel\BasicCurriculum.pas',
  Automaton in '..\Actors\Automaton.pas',
  FacIds in '..\Model Extensions\FacIds.pas',
  TownPolitics in '..\Kernel\TownPolitics.pas',
  WorldPolitics in '..\Kernel\WorldPolitics.pas',
  RDOLogAgents in '..\Kernel\RDOLogAgents.pas',
  Logs in '..\Logs\Logs.pas',
  Rankings in '..\Kernel\Rankings.pas',
  BasicRankings in '..\Kernel\BasicRankings.pas',
  StdRankings in '..\Kernel\StdRankings.pas',
  Inventions in '..\Inventions\Inventions.pas',
  Seasons in '..\Kernel\Seasons.pas',
  Profiler in '..\Kernel\Profiler.pas',
  Graphics in '..\Utils\VCL\graphics.pas',
  Events in '..\Kernel\Events.pas',
  BasicEvents in '..\Kernel\BasicEvents.pas',
  HostNames in '..\Utils\Network\HostNames.pas',
  GenIdd in '..\Utils\Serial\GenIdd.pas',
  RankProtocol in '..\Protocol\RankProtocol.pas',
  Languages in '..\Kernel\Languages.pas',
  SimMLS in '..\Kernel\SimMLS.pas',
  BackupObjects in '..\Persistence\BackupObjects.pas',
  TycoonLevels in '..\Kernel\TycoonLevels.pas',
  TranscendBlock in '..\StdBlocks\TranscendBlock.pas',
  CircuitEquivalences in '..\Circuits\CircuitEquivalences.pas',
  BackupThread in '..\Kernel\BackupThread.pas',
  LoggedUserData in '..\Kernel\LoggedUserData.pas',
  MediaGates in '..\Kernel\MediaGates.pas',
  MediaNameHistory in '..\Kernel\MediaNameHistory.pas',
  EconomyRelay in '..\Kernel\EconomyRelay.pas',
  TycoonVotes in '..\Kernel\TycoonVotes.pas',
  ClusterTask in '..\Tasks\ClusterTask.pas',
  CommonTasks in '..\Tasks\CommonTasks.pas',
  MakeProfitTask in '..\Tasks\MakeProfitTask.pas',
  ResearchTask in '..\Tasks\ResearchTask.pas',
  DissidentTutorial in '..\Tasks\DissidentTutorial.pas',
  MoabTutorial in '..\Tasks\MoabTutorial.pas',
  MarikoTutorial in '..\Tasks\MarikoTutorial.pas',
  ReachMatrix in '..\Circuits\ReachMatrix.pas',
  LoanMoneyTask in '..\Tasks\LoanMoneyTask.pas',
  DirectoryServerProtocol in '..\DServer\DirectoryServerProtocol.pas',
  CloneOptions in '..\Kernel\CloneOptions.pas';

{$R *.RES}

begin
  Application.Initialize;
  Application.Title := 'FIVE Model Server';
  Application.CreateForm(TModelServerReport, ModelServerReport);
  Application.Run;
end.

