unit DDrawErrors;

interface

  uses
    Windows;

  function GetErrorAsText(Error : HResult) : string;

implementation

  const
    cMaxErrors = 111;

  type
    TDirectDrawError =
      record
        Code : HResult;
        Text : string;
      end;

  const
    DDrawErrors : array [0 .. pred(cMaxErrors)] of TDirectDrawError =
      (
        (Code : DD_OK; Text : 'DD_OK'),
        (Code : DDERR_ALREADYINITIALIZED; Text : 'DDERR_ALREADYINITIALIZED'),
        (Code : DDERR_BLTFASTCANTCLIP; Text : 'DDERR_BLTFASTCANTCLIP'),
        (Code : DDERR_CANNOTATTACHSURFACE; Text : 'DDERR_CANNOTATTACHSURFACE'),
        (Code : DDERR_CANNOTDETACHSURFACE; Text : 'DDERR_CANNOTDETACHSURFACE'),
        (Code : DDERR_CANTCREATEDC; Text : 'DDERR_CANTCREATEDC'),
        (Code : DDERR_CANTDUPLICATE; Text : 'DDERR_CANTDUPLICATE'),
        (Code : DDERR_CANTLOCKSURFACE; Text : 'DDERR_CANTLOCKSURFACE'),
        (Code : DDERR_CANTPAGELOCK; Text : 'DDERR_CANTPAGELOCK'),
        (Code : DDERR_CANTPAGEUNLOCK; Text : 'DDERR_CANTPAGEUNLOCK'),
        (Code : DDERR_CLIPPERISUSINGHWND; Text : 'DDERR_CLIPPERISUSINGHWND'),
        (Code : DDERR_COLORKEYNOTSET; Text : 'DDERR_COLORKEYNOTSET'),
        (Code : DDERR_CURRENTLYNOTAVAIL; Text : 'DDERR_CURRENTLYNOTAVAIL'),
        (Code : DDERR_DCALREADYCREATED; Text : 'DDERR_DCALREADYCREATED'),
        (Code : DDERR_DEVICEDOESNTOWNSURFACE; Text : 'DDERR_DEVICEDOESNTOWNSURFACE'),
        (Code : DDERR_DIRECTDRAWALREADYCREATED; Text : 'DDERR_DIRECTDRAWALREADYCREATED'),
        (Code : DDERR_EXCEPTION; Text : 'DDERR_EXCEPTION'),
        (Code : DDERR_EXCLUSIVEMODEALREADYSET; Text : 'DDERR_EXCLUSIVEMODEALREADYSET'),
        (Code : DDERR_EXPIRED; Text : 'DDERR_EXPIRED'),
        (Code : DDERR_GENERIC; Text : 'DDERR_GENERIC'),
        (Code : DDERR_HEIGHTALIGN; Text : 'DDERR_HEIGHTALIGN'),
        (Code : DDERR_HWNDALREADYSET; Text : 'DDERR_HWNDALREADYSET'),
        (Code : DDERR_HWNDSUBCLASSED; Text : 'DDERR_HWNDSUBCLASSED'),
        (Code : DDERR_IMPLICITLYCREATED; Text : 'DDERR_IMPLICITLYCREATED'),
        (Code : DDERR_INCOMPATIBLEPRIMARY; Text : 'DDERR_INCOMPATIBLEPRIMARY'),
        (Code : DDERR_INVALIDCAPS; Text : 'DDERR_INVALIDCAPS'),
        (Code : DDERR_INVALIDCLIPLIST; Text : 'DDERR_INVALIDCLIPLIST'),
        (Code : DDERR_INVALIDDIRECTDRAWGUID; Text : 'DDERR_INVALIDDIRECTDRAWGUID'),
        (Code : DDERR_INVALIDMODE; Text : 'DDERR_INVALIDMODE'),
        (Code : DDERR_INVALIDOBJECT; Text : 'DDERR_INVALIDOBJECT'),
        (Code : DDERR_INVALIDPARAMS; Text : 'DDERR_INVALIDPARAMS'),
        (Code : DDERR_INVALIDPIXELFORMAT; Text : 'DDERR_INVALIDPIXELFORMAT'),
        (Code : DDERR_INVALIDPOSITION; Text : 'DDERR_INVALIDPOSITION'),
        (Code : DDERR_INVALIDRECT; Text : 'DDERR_INVALIDRECT'),
        (Code : DDERR_INVALIDSTREAM; Text : 'DDERR_INVALIDSTREAM'),
        (Code : DDERR_INVALIDSURFACETYPE; Text : 'DDERR_INVALIDSURFACETYPE'),
        (Code : DDERR_LOCKEDSURFACES; Text : 'DDERR_LOCKEDSURFACES'),
        (Code : DDERR_MOREDATA; Text : 'DDERR_MOREDATA'),
        (Code : DDERR_NO3D; Text : 'DDERR_NO3D'),
        (Code : DDERR_NOALPHAHW; Text : 'DDERR_NOALPHAHW'),
        (Code : DDERR_NOBLTHW; Text : 'DDERR_NOBLTHW'),
        (Code : DDERR_NOCLIPLIST; Text : 'DDERR_NOCLIPLIST'),
        (Code : DDERR_NOCLIPPERATTACHED; Text : 'DDERR_NOCLIPPERATTACHED'),
        (Code : DDERR_NOCOLORCONVHW; Text : 'DDERR_NOCOLORCONVHW'),
        (Code : DDERR_NOCOLORKEY; Text : 'DDERR_NOCOLORKEY'),
        (Code : DDERR_NOCOLORKEYHW; Text : 'DDERR_NOCOLORKEYHW'),
        (Code : DDERR_NOCOOPERATIVELEVELSET; Text : 'DDERR_NOCOOPERATIVELEVELSET'),
        (Code : DDERR_NODC; Text : 'DDERR_NODC'),
        (Code : DDERR_NODDROPSHW; Text : 'DDERR_NODDROPSHW'),
        (Code : DDERR_NODIRECTDRAWHW; Text : 'DDERR_NODIRECTDRAWHW'),
        (Code : DDERR_NODIRECTDRAWSUPPORT; Text : 'DDERR_NODIRECTDRAWSUPPORT'),
        (Code : DDERR_NOEMULATION; Text : 'DDERR_NOEMULATION'),
        (Code : DDERR_NOEXCLUSIVEMODE; Text : 'DDERR_NOEXCLUSIVEMODE'),
        (Code : DDERR_NOFLIPHW; Text : 'DDERR_NOFLIPHW'),
        (Code : DDERR_NOFOCUSWINDOW; Text : 'DDERR_NOFOCUSWINDOW'),
        (Code : DDERR_NOGDI; Text : 'DDERR_NOGDI'),
        (Code : DDERR_NOHWND; Text : 'DDERR_NOHWND'),
        (Code : DDERR_NOMIPMAPHW; Text : 'DDERR_NOMIPMAPHW'),
        (Code : DDERR_NOMIRRORHW; Text : 'DDERR_NOMIRRORHW'),
        (Code : DDERR_NONONLOCALVIDMEM; Text : 'DDERR_NONONLOCALVIDMEM'),
        (Code : DDERR_NOOPTIMIZEHW; Text : 'DDERR_NOOPTIMIZEHW'),
        (Code : DDERR_NOOVERLAYDEST; Text : 'DDERR_NOOVERLAYDEST'),
        (Code : DDERR_NOOVERLAYHW; Text : 'DDERR_NOOVERLAYHW'),
        (Code : DDERR_NOPALETTEATTACHED; Text : 'DDERR_NOPALETTEATTACHED'),
        (Code : DDERR_NOPALETTEHW; Text : 'DDERR_NOPALETTEHW'),
        (Code : DDERR_NORASTEROPHW; Text : 'DDERR_NORASTEROPHW'),
        (Code : DDERR_NOROTATIONHW; Text : 'DDERR_NOROTATIONHW'),
        (Code : DDERR_NOSTRETCHHW; Text : 'DDERR_NOSTRETCHHW'),
        (Code : DDERR_NOT4BITCOLOR; Text : 'DDERR_NOT4BITCOLOR'),
        (Code : DDERR_NOT4BITCOLORINDEX; Text : 'DDERR_NOT4BITCOLORINDEX'),
        (Code : DDERR_NOT8BITCOLOR; Text : 'DDERR_NOT8BITCOLOR'),
        (Code : DDERR_NOTAOVERLAYSURFACE; Text : 'DDERR_NOTAOVERLAYSURFACE'),
        (Code : DDERR_NOTEXTUREHW; Text : 'DDERR_NOTEXTUREHW'),
        (Code : DDERR_NOTFLIPPABLE; Text : 'DDERR_NOTFLIPPABLE'),
        (Code : DDERR_NOTFOUND; Text : 'DDERR_NOTFOUND'),
        (Code : DDERR_NOTINITIALIZED; Text : 'DDERR_NOTINITIALIZED'),
        (Code : DDERR_NOTLOADED; Text : 'DDERR_NOTLOADED'),
        (Code : DDERR_NOTLOCKED; Text : 'DDERR_NOTLOCKED'),
        (Code : DDERR_NOTPAGELOCKED; Text : 'DDERR_NOTPAGELOCKED'),
        (Code : DDERR_NOTPALETTIZED; Text : 'DDERR_NOTPALETTIZED'),
        (Code : DDERR_NOVSYNCHW; Text : 'DDERR_NOVSYNCHW'),
        (Code : DDERR_NOZBUFFERHW; Text : 'DDERR_NOZBUFFERHW'),
        (Code : DDERR_NOZOVERLAYHW; Text : 'DDERR_NOZOVERLAYHW'),
        (Code : DDERR_OUTOFCAPS; Text : 'DDERR_OUTOFCAPS'),
        (Code : DDERR_OUTOFMEMORY; Text : 'DDERR_OUTOFMEMORY'),
        (Code : DDERR_OUTOFVIDEOMEMORY; Text : 'DDERR_OUTOFVIDEOMEMORY'),
        (Code : DDERR_OVERLAPPINGRECTS; Text : 'DDERR_OVERLAPPINGRECTS'),
        (Code : DDERR_OVERLAYCANTCLIP; Text : 'DDERR_OVERLAYCANTCLIP'),
        (Code : DDERR_OVERLAYCOLORKEYONLYONEACTIVE; Text : 'DDERR_OVERLAYCOLORKEYONLYONEACTIVE'),
        (Code : DDERR_OVERLAYNOTVISIBLE; Text : 'DDERR_OVERLAYNOTVISIBLE'),
        (Code : DDERR_PALETTEBUSY; Text : 'DDERR_PALETTEBUSY'),
        (Code : DDERR_PRIMARYSURFACEALREADYEXISTS; Text : 'DDERR_PRIMARYSURFACEALREADYEXISTS'),
        (Code : DDERR_REGIONTOOSMALL; Text : 'DDERR_REGIONTOOSMALL'),
        (Code : DDERR_SURFACEALREADYATTACHED; Text : 'DDERR_SURFACEALREADYATTACHED'),
        (Code : DDERR_SURFACEALREADYDEPENDENT; Text : 'DDERR_SURFACEALREADYDEPENDENT'),
        (Code : DDERR_SURFACEBUSY; Text : 'DDERR_SURFACEBUSY'),
        (Code : DDERR_SURFACEISOBSCURED; Text : 'DDERR_SURFACEISOBSCURED'),
        (Code : DDERR_SURFACELOST; Text : 'DDERR_SURFACELOST'),
        (Code : DDERR_SURFACENOTATTACHED; Text : 'DDERR_SURFACENOTATTACHED'),
        (Code : DDERR_TOOBIGHEIGHT; Text : 'DDERR_TOOBIGHEIGHT'),
        (Code : DDERR_TOOBIGSIZE; Text : 'DDERR_TOOBIGSIZE'),
        (Code : DDERR_TOOBIGWIDTH; Text : 'DDERR_TOOBIGWIDTH'),
        (Code : DDERR_UNSUPPORTED; Text : 'DDERR_UNSUPPORTED'),
        (Code : DDERR_UNSUPPORTEDFORMAT; Text : 'DDERR_UNSUPPORTEDFORMAT'),
        (Code : DDERR_UNSUPPORTEDMASK; Text : 'DDERR_UNSUPPORTEDMASK'),
        (Code : DDERR_UNSUPPORTEDMODE; Text : 'DDERR_UNSUPPORTEDMODE'),
        (Code : DDERR_VERTICALBLANKINPROGRESS; Text : 'DDERR_VERTICALBLANKINPROGRESS'),
        (Code : DDERR_VIDEONOTACTIVE; Text : 'DDERR_VIDEONOTACTIVE'),
        (Code : DDERR_WASSTILLDRAWING; Text : 'DDERR_WASSTILLDRAWING'),
        (Code : DDERR_WRONGMODE; Text : 'DDERR_WRONGMODE'),
        (Code : DDERR_XALIGN; Text : 'DDERR_XALIGN')
      );

  function GetErrorAsText(Error : HResult) : string;
    var
      i : integer;
    begin
      i := 0;
      Found := false;
      while (i < cMaxErrors) and not Found do
        begin
          Found := DDrawErrors[i].Code = Error;
          if not Found
            then inc(i);
        end;
      if i < cMaxErrors
        then Result := DDrawError[i].Text
        else Result := 'Unknown error';
    end;

end.
